version: "3"

services: 
    db:
        image: mongo:latest
        container_name: chsf-mongodb

    php:
        build: .
        
        container_name: chsf-phpmongo
        volumes:
            - ./:/var/www/html/
        ports:
            - "80:80"
        links:
            - db
        command: apt-get update \
            && apt-get install -y autoconf pkg-config libssl-dev \
            && pecl install mongodb-1.2.2 \
            && docker-php-ext-install bcmath \
            && echo "extension=mongodb.so" >> /usr/local/etc/php/conf.d/mongodb.ini